---
title: TECHNO KANXA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A Blog For Science and Technology Enthusiast
keywords: Technokanxa, technology, technology nepal
author: Bishwop Prakash Dhakal
baseurl: 
url: 
